blog/web/views.py
import math

from flask import Blueprint, request, render_template,redirect,\
    url_for
from flask.json import jsonify
from sqlalchemy import or_,and_,not_

from back.models import Article, Atc_type

# 第一步: 生成蓝图对象
# 蓝图用于管理路由
wblue = Blueprint('web', __name__)



# 默认渲染分页第一页
def default_page():
    atcs_all = Article.query.filter().all()
    pages = list(range(math.ceil(len(atcs_all) / 5)))  # 计算应该显示的页数
    # 默认显示第一页的数据
    atcs = Article.query.order_by(-Article.create_time).offset(0).limit(5).all()
    res = [atcs_all, pages, atcs]
    return res

# ajax分页
def ajax_page(atcs):
    atcss = []
    for atc in atcs:
        atc_dict = {}
        atc_dict['id'] = atc.id
        atc_dict['title'] = atc.title
        atc_dict['desc'] = atc.desc
        atc_dict['content'] = atc.content
        atc_dict['create_time'] = atc.create_time.strftime('%Y-%m-%d %X')
        atc_dict['type'] = atc.type  # type保存的时类型的id
        atc_dict['uid'] = atc.uid
        atc_dict['tname'] = atc.tp.tname  # 获取类型名
        atcss.append(atc_dict)
    # return jsonify({'status':200})
    return jsonify({'atcss': atcss})



# 网站主页
@wblue.route('/home/',methods=['GET'])
def home():
    # 显示左侧栏目分类
    types = Atc_type.query.filter().all()
    res = default_page()
    return render_template('web/home.html', types=types, pages=res[1], atcs=res[2])


# 相册
@wblue.route('/photo/',methods=['GET'])
def photo():

    return render_template('web/photo.html')


# 文章分享主页
@wblue.route('/share/',methods=['GET','POST'])
def share():
    if request.method == 'GET':
        # 显示左侧文章分类
        types = Atc_type.query.filter().all()
        # 最近更新
        recent_atcs = Article.query.order_by(-Article.create_time).offset(0).limit(8).all()
        # 默认显示第一页文章数据
        res = default_page()
        return render_template('web/share.html', types=types, pages=res[1], atcs=res[2],recent_atcs=recent_atcs)

    if request.method == 'POST':
        page = int(request.form.get('page'))
        atcs = Article.query.order_by(-Article.create_time).offset((page - 1) * 5).limit(5).all()
        return ajax_page(atcs)


# 所选栏目的所有文章界面
@wblue.route('/share/<string:tname>/',methods=['GET', 'POST'])
def category(tname):
    if request.method == 'GET':
        # 显示左侧栏目分类
        types = Atc_type.query.filter().all()
        # 显示该类所有文章
        type = Atc_type.query.filter(Atc_type.tname == tname).first() #查找到指定类的对象
        pages = list(range(math.ceil(len(type.atcs) / 5)))  # 计算应该显示的页数
        # 默认显示第一页的数据
        atcs = Article.query.filter(Article.type==type.id).order_by(-Article.create_time).offset(0).limit(5).all()
        # 最近更新
        recent_atcs = Article.query.order_by(-Article.create_time).offset(0).limit(8).all()
        return render_template('web/share.html', atcs=atcs, types=types, pages=pages, recent_atcs=recent_atcs)  #类型对象.关联关系(atcs) 得到所有该类文章
    if request.method == 'POST':
        page = int(request.form.get('page'))
        type = Atc_type.query.filter(Atc_type.tname == tname).first()  # 查找到指定类的对象
        atcs = Article.query.filter(Article.type==type.id).order_by(-Article.create_time).offset((page - 1) * 5).limit(5).all()
        return ajax_page(atcs)


# 显示选定文章的内容界面
@wblue.route('/share/show_atc/<int:id>/',methods=['GET'])
def show_atc(id):
    # 显示左侧栏目分类
    types = Atc_type.query.filter().all()
    # 显示文章内容
    atc = Article.query.filter(Article.id == id).first()
    # 最近更新
    recent_atcs = Article.query.order_by(-Article.create_time).offset(0).limit(8).all()
    return render_template('web/share.html', atc=atc, types=types, recent_atcs=recent_atcs)


# 关于我
@wblue.route('/about/',methods=['GET'])
def about():
        return render_template('web/about.html')


@wblue.route('/info/',methods=['GET'])
def info():
        return render_template('web/info.html')

blog/templates/web/about.html
{% extends 'web/base_main.html' %}


{% block title %}
    关于我-Deaseyy个人博客
{% endblock %}

{% block css %}
{{ super() }}
<link rel="icon" href="/static/web/images/tomcat.ico" type="image/x-icon">
<link rel="shortcut icon" href="/static/web/images/tomcat.ico" type="image/x-icon">
{% endblock %}


{% block search %}

{% endblock %}


{% block fenlei %}

{% endblock %}


{% block content %}
  <div class="r_box">
     <ul class="about">
      <p>一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。我入行早，大家也亲切的叫我&ldquo;青姐&rdquo;。<br />
           <br />
            SEO奋斗了将近两年时间，个人博客网站百度排名也从之前的30页后，排到了第一页。期间有很多的不容易，但是都没有放弃过。入了这一行，就深深的喜欢上它。我喜欢一句话&ldquo;冥冥中该来则来，无处可逃&rdquo;。<br />
            <br />
    <img src="../../static/web/images/1.jpg">        近几年我也发现个人博客排前几页的也有很多是我做过的模板，感谢各位站长的欣赏，我仔细看过他们的网站。他们在我原模板的基础上有修改，而且他们做的原创内容都是值得一读的。有时候甚至排名都超过了我个人博客网站的排名。<br />
            <br />
          <h2>About my blog</h2>
          &nbsp;

     </ul>
  </div>
{% endblock %}

blog/templates/web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>

        {% block css %}

        {% endblock %}

</head>
<body>

     {% block header %}

     {% endblock %}


    <article>
        <div class="l_box">

            {% block about %}

            {% endblock %}


            {% block wdxc %}

            {% endblock %}


            {% block search %}

            {% endblock %}


            {% block fenlei %}

            {% endblock %}


            {% block cloud %}

            {% endblock %}


            {% block recent %}

            {% endblock %}



            {% block links %}

            {% endblock %}



        </div>


        {% block content %}

        {% endblock %}




    </article>



    {% block footer %}

    {% endblock %}


    {% block js %}

    {% endblock %}

</body>
</html>

blog/templates/web/base_main.html
{% extends 'web/base.html' %}


{% block css %}
    <link href="/static/web/css/base.css" rel="stylesheet">
    <link href="/static/web/css/index.css" rel="stylesheet">
    <link href="/static/web/css/info.css" rel="stylesheet">
    <link href="/static/web/css/m.css" rel="stylesheet">

    <script src="/static/web/js/jquery.min.js" type="text/javascript"></script>

{% endblock %}



{% block header %}
    <header>
    <div class="logo"><a href="{{ url_for('first.index') }}">Deaseyy个人博客</a></div>
    <nav id="nav">

        <ul>
            <li><a href="/web/home/">网站首页</a></li>
            <li><a href="/web/photo/">我的相册</a></li>
            <li><a href="/web/share">我的分享</a></li>
            <li><a href="/web/about/">关于我</a></li>
            <li><a href="/web/info/">内容页</a></li>
        </ul>

    </nav>

    <script>
        window.onload = function () {
            var obj = null;
            var As = document.getElementById('nav').getElementsByTagName('a');
            obj = As[0];
            for (i = 1; i < As.length; i++) {
                if (window.location.href.indexOf(As[i].href) >= 0)
                    obj = As[i];
            }
            obj.id = 'selected'
        }
    </script>
</header>
{% endblock %}


{% block about %}
    <div class="about_me">
            <h2>关于我</h2>
            <ul>
                <i><img height="90" src="/static/web/images/tomcat.ico"></i>
                <p><b>Deaseyy:</b> 一个成长中的python开发者</p>
            </ul>
        </div>
{% endblock %}


{% block wdxc %}
    <div class="wdxc">
            <h2>我的相册</h2>
            <ul>
                <li><a href="/"><img src="/static/web/images/7.jpg"></a></li>
                <li><a href="/"><img src="/static/web/images/8.jpg"></a></li>
                <li><a href="/"><img src="/static/web/images/9.jpg"></a></li>
                <li><a href="/"><img src="/static/web/images/10.jpg"></a></li>
                <li><a href="/"><img src="/static/web/images/11.jpg"></a></li>
                <li><a href="/"><img src="/static/web/images/12.jpg"></a></li>
            </ul>
        </div>
{% endblock %}


{% block search %}
    <div class="search">
            <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
                <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词"
                       style="color: rgb(153, 153, 153);"
                       onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}"
                       onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
                <input name="show" value="title" type="hidden">
                <input name="tempid" value="1" type="hidden">
                <input name="tbname" value="news" type="hidden">
                <input name="Submit" class="input_submit" value="搜索" type="submit">
            </form>
        </div>
{% endblock %}


{% block fenlei %}
<div class="fenlei">
    <h2>文章分类</h2>
    <ul>
        <!--进入页面时循环显示左侧所有栏目-->
        {% if types %}
            {% for type in types %}
            <li><a href="{{ url_for('web.category', tname=type.tname) }}">{{ type.tname }}</a></li>
            {% endfor %}
        {% endif %}

    </ul>
</div>
{% endblock %}





{% block footer %}
  <p style="text-align: center"> Deaseyy个人博客 </p>
{% endblock %}

blog/templates/web/home.html
{% extends 'web/base_main.html' %}


{% block title %}
    首页-Deaseyy个人博客
{% endblock %}


{% block css %}
{{ super() }}
<link rel="icon" href="/static/web/images/tomcat.ico" type="image/x-icon">
<link rel="shortcut icon" href="/static/web/images/tomcat.ico" type="image/x-icon">
{% endblock %}


{% block links %}
<div class="links">
    <h2>友情链接</h2>
    <ul>
       <a href="http://www.yangqq.com">杨青个人博客</a> <a href="http://www.yangqq.com">杨青博客</a>
    </ul>
</div>
{% endblock %}



{% block content %}
<div  class="r_box">

    <!--默认显示分页第一页-->
        {% if atcs %}
        <ul id="article">
          {% for atc in atcs %}
            <li>
              <i><a href="{{ url_for('web.show_atc', id=atc.id) }}"><img src="/static/web/images/2.jpg"></a></i>
              <h3><a href="{{ url_for('web.show_atc', id=atc.id) }}"> {{ atc.title }} </a></h3>
              <p>{{ atc.desc }}</p>
            </li>

          {% endfor %}
        </ul>
        {% endif %}

<div style="text-align: center;"> <a style="color: #0785d1;" href="{{ url_for('web.share') }}"> 查看更多>></a> </div>
</div>
{% endblock %}



{% block page %}

{% endblock %}



{% block js %}
<script src="/static/web/js/jquery.min.js">  </script>
<script src="/static/web/js/ydspage.js"></script>
{% endblock %}

blog/templates/web/share.html
{% extends 'web/base_main.html' %}

{% block title %}
  分享-Deaseyy个人博客
{% endblock %}

{% block css %}
{{ super() }}
<link rel="icon" href="/static/web/images/tomcat.ico" type="image/x-icon">
<link rel="shortcut icon" href="/static/web/images/tomcat.ico" type="image/x-icon">
{% endblock %}



{% block about %}

{% endblock %}


{% block wdxc %}

{% endblock %}


{% block cloud %}
<div class="cloud">
    <h2>标签云</h2>
    <ul>
     <a href="/">陌上花开</a> <a href="/">校园生活</a> <a href="/">html5</a> <a href="/">SumSung</a> <a href="/">青春</a> <a href="/">温暖</a> <a href="/">阳光</a> <a href="/">三星</a><a href="/">索尼</a> <a href="/">华维荣耀</a> <a href="/">三星</a> <a href="/">索尼</a>
    </ul>
 </div>
{% endblock %}


{% block recent %}
<div class="tuijian">
    <h2>最近更新</h2>
    <ul>
        {% for atc in recent_atcs %}
            <li><a href="{{ url_for('web.show_atc', id=atc.id) }}">{{ atc.title }}</a></li>
        {% endfor %}
    </ul>
</div>
{% endblock %}



{% block content %}
<div class="r_box">
    <!--默认显示分页第一页-->
    {% if atcs %}
    <ul id="article">
      {% for atc in atcs %}
        <li>
          <i><a href="{{ url_for('web.show_atc', id=atc.id) }}"><img src="/static/web/images/2.jpg"></a></i>
          <h3><a href="{{ url_for('web.show_atc', id=atc.id) }}"> {{ atc.title }} </a></h3>
          <p>{{ atc.desc }}</p>
        </li>

      {% endfor %}
    </ul>

    <!--分页-->
    <div id="yema" style="width: 773px;" class="pagelist">
        {% for page in pages %}
            {% if loop.first  %}      {# loop.first:是否第一次循环,等同page=0时 #}
               <a class="curPage">{{ page+1 }}</a>&nbsp;&nbsp;
                {% else %}
                    <a>{{ page+1 }}</a>&nbsp;&nbsp;
            {% endif %}
         {% endfor %}
          <!--<span >下一页</span>-->
    </div>
    {% endif %}


</div>

<!--文章内容显示界面-->
{% if atc %}
 <main>
<div class="infosbox">
  <div class="newsview">
    <h3 class="news_title" style="text-align: center"> {{ atc.title }} </h3>
    <div class="bloginfo">
      <ul>
        <li class="author">作者：<a href="{{ url_for('web.about') }}">Deaseyy</a></li>
        <li class="lmname">分类: <a href="{{ url_for('web.category', tname=atc.tp.tname) }}">{{ atc.tp.tname }}</a></li>
        <li class="timer">时间：{{ atc.create_time }}</li>
        <li class="view">4567人已阅读</li>
      </ul>
    </div>
    <div class="tags"><a href="/" target="_blank">个人博客</a> &nbsp; <a href="/" target="_blank">小世界</a></div>
    <div class="news_about"><strong>简介</strong>个人博客，主要用来记录学习和工作过程中的一些心得和笔记，也会放上一些照片，音乐。每天工作回家后就能访问自己的网站，一边听着音乐，一边记录。</div>
    <div class="news_con">
        {{ atc.content | safe }}

    </div>
  </div>
  <div class="share">
    <p class="diggit"><a href="JavaScript:makeRequest('/e/public/digg/?classid=3&amp;id=19&amp;dotop=1&amp;doajax=1&amp;ajaxarea=diggnum','EchoReturnedText','GET','');"> 很赞哦！ </a>(<b id="diggnum"><script type="text/javascript" src="/e/public/ViewClick/?classid=2&id=20&down=5"></script>13</b>)</p>
  </div>
  <div class="nextinfo">
    <p>上一篇：<a href="/news/life/2018-03-13/804.html">作为一个设计师,如果遭到质疑你是否能恪守自己的原则?</a></p>
    <p>下一篇：<a href="/news/life/">返回列表</a></p>
  </div>
  <div class="news_pl">
    <h2>文章评论</h2>
    <div class="gbko">
      <script src="/e/pl/more/?classid=77&amp;id=106&amp;num=20"></script>
      <div class="fb">
        <ul>
          <p class="fbtime"><span>2018-07-24 11:52:38</span>dancesmile</p>
          <p class="fbinfo">这才是我要的朋友圈</p>
        </ul>
      </div>
      <div class="fb">
        <ul>
          <p class="fbtime"><span>2018-07-24 08:52:48</span> 卜野</p>
          <p class="fbinfo"></p>
          <div class="ecomment"><span class="ecommentauthor">网友 家蚂蚁 的原文：</span>
            <p class="ecommenttext">坚持哟!看你每天都有写，请继续加油，再接再厉哦</p>
          </div>
        </ul>
      </div>

      <script>
      function CheckPl(obj)
      {
      if(obj.saytext.value=="")
      {
      alert("您没什么话要说吗？");
      obj.saytext.focus();
      return false;
      }
      return true;
      }
      </script>
      <form action="/e/pl/doaction.php" method="post" name="saypl" id="saypl" onsubmit="return CheckPl(document.saypl)">
        <div id="plpost">
          <p class="saying"><span><a href="/e/pl/?classid=77&amp;id=106">共有<script type="text/javascript" src="/e/public/ViewClick/?classid=77&amp;id=106&amp;down=2"></script>2条评论</a></span>来说两句吧...</p>
          <p class="yname"><span>用户名:</span>
            <input name="username" type="text" class="inputText" id="username" value="" size="16">
          </p>
          <p class="yzm"><span>验证码:</span>
            <input name="key" type="text" class="inputText" size="16">
          </p>
          <input name="nomember" type="hidden" id="nomember" value="1" checked="checked">
          <textarea name="saytext" rows="6" id="saytext"></textarea>
          <input name="imageField" type="submit" value="提交">
          <input name="id" type="hidden" id="id" value="106">
          <input name="classid" type="hidden" id="classid" value="77">
          <input name="enews" type="hidden" id="enews" value="AddPl">
          <input name="repid" type="hidden" id="repid" value="0">
          <input type="hidden" name="ecmsfrom" value="/joke/talk/2018-07-23/106.html">
        </div>
      </form>
    </div>
  </div>
</div>
</main>
{% endif %}

{% endblock %}





{% block js %}
<script src="/static/web/js/jquery.min.js">  </script>
<script src="/static/web/js/ydspage.js"></script>

<script>
window.onload = function ()
{
var obj=null;
var As=document.getElementById('nav').getElementsByTagName('a');
obj = As[0];
for(i=1;i<As.length;i++){if(window.location.href.indexOf(As[i].href)>=0)
obj=As[i];}
obj.id='selected'
}

</script>
<script type="text/javascript">
$(document).ready(function(e) {
	t = $('.tuijian').offset().top;
	mh = $('.infosbox').height();
	fh = $('.tuijian').height();
	gh = $('.guanzhu').height();
	$(window).scroll(function(e){
		s = $(document).scrollTop();
		if(s > t - 10){
			$('.tuijian').css('position','fixed');

			if(s + fh > mh){
				$('.tuijian').css('top',mh-s-fh+'px');
			}
		}else{
			$('.tuijian').css('position','');
		}
		if(s > t - 10){
			$('.guanzhu').css('position','fixed');
			if(s + gh > mh){
				$('.guanzhu').css('top',mh-s-gh+'px');
			}
		}else{
			$('.guanzhu').css('position','');
		}
	})
});
</script>

{% endblock %}