blog/back/models.py
from datetime import datetime

from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(30), unique=True)
    pwd = db.Column(db.String(255))
    isdelete = db.Column(db.Boolean, default=False)
    create_time = db.Column(db.DateTime, default=datetime.now)
    atcs = db.relationship('Article', backref='u')
    __tablename__ = 'user'  #定义表名,可不写,默认为模型名的小写user

    def save_update(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()


class Atc_type(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    tname = db.Column(db.String(100))
    keyword = db.Column(db.String(100))
    desc = db.Column(db.String(255))
    atcs = db.relationship('Article', backref='tp')
    __tablename__ = 'atc_type'

    def save_update(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()


class Article(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True, nullable=False)
    title = db.Column(db.String(50), unique=True, nullable=False)
    desc = db.Column(db.String(150))
    content = db.Column(db.Text,nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.now)
    type = db.Column(db.Integer, db.ForeignKey('atc_type.id'), nullable=False)
    uid = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    __tablename__ = 'article'

    def save_update(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

blog/back/views.py
import math

from flask import Blueprint, request, render_template, redirect, \
    url_for, session, jsonify
from sqlalchemy import or_,and_,not_
from werkzeug.security import generate_password_hash, check_password_hash

from back.models import db, User, Article, Atc_type
from utils.functions import login_required  # 导入装饰器

# 第一步: 生成蓝图对象
# 蓝图用于管理路由


bblue = Blueprint('first',__name__)

# 第三步: 使用蓝图对象管理路由
@bblue.route('/index/', methods=['GET'])
@login_required  # 校验登陆
def index():
    atcs = Article.query.filter().all()
    users = User.query.filter().all()
    return render_template('back/index.html', atcs=atcs, users=users)


# 增加文章
@bblue.route('/add-article/', methods=['GET','POST'])
@login_required
def add_article():
    if request.method == 'GET':
        # 显示所有栏目分类到后台页面
        types = Atc_type.query.filter().all()
        return render_template('back/add-article.html', types=types)

    if request.method == 'POST':
        atc = Article()
        # 获取前端页面填写的数据
        atc.title = request.form.get('title')
        atc.desc = request.form.get('describe')
        atc.content = request.form.get('content')
        atc.type = int(request.form.get('category'))
        atc.uid = session.get('user_id')  # 从session中获取正在登陆的用户id
        # 存入数据库时,判断数据合法性
        res_title = Article.query.filter(Article.title==atc.title).first()
        if atc.title==None or res_title:
            error = '标题为空或已存在!'
            return render_template('back/add-article.html', title_err=error)
        if not atc.content:
            error = '内容不能为空!'
            return render_template('back/add-article.html', content_err=error)
        atc.save_update()
        return redirect(url_for('first.article'))


# 文章界面
@bblue.route('/article/',methods=['GET','POST'])
@login_required  # 校验登陆
def article():
    if request.method == 'GET':
        atcs_all = Article.query.filter().all()
        pages = list(range(math.ceil(len(atcs_all)/3)))  # 计算应该显示的页数
        # 默认显示第一页的数据
        atcs = Article.query.offset(0).limit(3).all()
        return render_template('back/article.html', atcs=atcs, pages=pages, atcs_all=atcs_all)

    if request.method == 'POST':
        page = int(request.form.get('page'))
        atcs = Article.query.offset((page - 1) * 3).limit(3).all()
        atcss = []
        for atc in atcs:
            atc_dict = {}
            atc_dict['id'] =atc.id
            atc_dict['title'] = atc.title
            atc_dict['desc'] = atc.desc
            atc_dict['content'] = atc.content
            atc_dict['create_time'] = atc.create_time.strftime('%Y-%m-%d %X')
            atc_dict['type'] = atc.type        # type保存的时类型的id
            atc_dict['uid'] = atc.uid
            atc_dict['tname'] = atc.tp.tname    # 获取类型名

            atcss.append(atc_dict)
        # return jsonify({'status':200})
        return jsonify({'atcss':atcss})



# 修改文章
@bblue.route('/update-article/<int:id>/',methods=['GET','POST'])
@login_required  # 校验登陆
def update_article(id):
    if request.method == 'GET':
        # 循环
        # 显示所有栏目分类到后台页面
        types = Atc_type.query.filter().all()
        # 显示需要修改的文章到后台页面
        atc_res = Article.query.filter(Article.id==id).first()
        return render_template('back/update-article.html', update_types=types, update_atc=atc_res )

    if request.method == 'POST':
        atc_res = Article.query.filter(Article.id == id).first()  # 找到修改对象对应的id,id由前端页面反向解析传回
        # 从网页表单获取数据
        title = request.form.get('title')
        content = request.form.get('content')
        desc = request.form.get('describe')
        type = request.form.get('category')
        # 保存修改数据
        atc_res.title = title
        atc_res.content = content
        atc_res.desc = desc
        atc_res.type = type
        atc_res.save_update()
        return redirect(url_for('first.article'))


# 删除单个文章
@bblue.route('/del-atc/<int:id>/',methods=['GET'])
@login_required  # 校验登陆
def del_atc(id):
    atc_res = Article.query.filter(Article.id == id).first()
    atc_res.delete()
    return redirect(url_for('first.article'))


# 删除所有勾选文章
@bblue.route('/del_all_atc/',methods=['GET','POST'])
@login_required  # 校验登陆
def del_all_atc():
    if request.method == 'POST':
        id_list = request.form.getlist('checkbox[]')  #getlist获取复选框提交的多个数据
        for id in id_list:
            atc_res = Article.query.filter(Article.id == id).first()
            atc_res.delete()
        return redirect(url_for('first.article'))


#栏目(文章分类)
@bblue.route('/category/', methods=['GET','POST'])
@login_required  # 校验登陆
def category():
    if request.method == 'GET':
        atc_types_res = Atc_type.query.filter().all()
        return render_template('back/category.html', atc_types=atc_types_res)  # 网页里传值传左边变量

    if request.method == 'POST':
        atc_type = Atc_type()   # 创建模型对象,即表的实体对象
        name = request.form.get('name')  # name:input输入框的name='name'属性对应值,取后者name变量
        keyword = request.form.get('keywords')
        describle = request.form.get('describe')
        atc_type.tname = name
        atc_type.keyword = keyword
        atc_type.desc = describle
        atc_type.save_update()  # 提交保存
        atc_types = Atc_type.query.filter().all()  #查找数据渲染到前端页面
        return render_template('back/category.html', atc_types=atc_types)


# 修改栏目
@bblue.route('/update-category/<int:id>/', methods=['GET','POST'])
@login_required  # 校验登陆
def update_category(id):  # id由前端页面点击链接url_for()反向解析传回
    if request.method == 'GET':
        res_type = Atc_type.query.filter(Atc_type.id == id).first()
        return render_template('back/update-category.html', update_type=res_type)

    if request.method == 'POST':
        atc_type_res = Atc_type.query.filter(Atc_type.id == id).first()  # 找到修改对象对应的id,id由前端页面反向解析传回
        # 从网页表单获取数据
        name = request.form.get('name')
        keyword = request.form.get('keywords')
        desc = request.form.get('describe')
        #保存数据
        atc_type_res.tname = name
        atc_type_res.keyword = keyword
        atc_type_res.desc = desc
        atc_type_res.save_update()
        return redirect(url_for('first.category'))


# 删除栏目
@bblue.route('/del_type/<int:id>/',methods=['GET'])
@login_required  # 校验登陆
def del_type(id):
    atc_type_res = Atc_type.query.filter(Atc_type.id == id).first()
    atc_type_res.delete()
    return redirect(url_for('first.category'))


# 登陆
@bblue.route('/login/',methods=['GET','POST'])
def login():
    if request.method == 'GET':   # 直接get请求访问/login,渲染登陆页面
        # 访问该路由时,若返回get请求参数 exit==exit,执行退出登录操作
        if request.args.get('exit') == 'exit':
            session.pop('user_id')  #  删除session
            return redirect(url_for('first.login')) #退出登陆时,进入该路由地址带有参数, 重定向到/login/

        # 访问该路由时,从装饰器中返回get请求参数 error==error,渲染带有参数的login页面
        if request.args.get('error') == 'error':
            err = '未登录,请先登录!'
            return render_template('back/login.html',err=err)

        return render_template('back/login.html')

    if request.method == 'POST':  # 当有post请求提交到/login时,执行该语句,校验成功后,渲染主页面,结束
        # time.sleep(5)
        username = request.form.get('username')
        password = request.form.get('userpwd')
        user_res = User.query.filter(User.name == username).first() #查询
        if user_res == None:
            error = '账号不存在,请验证后再试!'
            return render_template('back/login.html', err=error)

        # if user_res.pwd != password:
        # 第一个参数写加密过的hash值,第二个写需要和它匹配的参数
        if check_password_hash(user_res.pwd,password) == False: #解密检测,相等返回True
            error = '密码错误,请重新输入!'
            return render_template('back/login.html', err=error)
        # 设置session存储的用户,需开头定义加密方式 app.secret_key = '随便写'
        session['user_id'] = user_res.id  # 将用户id存入session
        return redirect(url_for('first.index'))


# 注册
@bblue.route('/register/',methods=['GET','POST'])
def register():
    if request.method == 'GET':
        return render_template('back/register.html')
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('userpwd')
        password2 = request.form.get('userpwd2')
        if username and password and password2: #判断输入数据是否有为空
            user_res = User.query.filter(User.name == username).first()
            if user_res:  # 判断是否注册
                error = '该用户名已注册,请更换!'
                return render_template('back/register.html', err=error) #error需要页面的{{error}}接收
            if password != password2:
                error = '重复密码不一致!'
                return render_template('back/register.html', err=error)
            #保存用户
            user = User()
            user.name = username
            user.pwd = generate_password_hash(password) #加密保存到数据库
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('first.login'))
        return render_template('back/register.html')


# 修改个人信息(密码等,id,name不能修改)
@bblue.route('/info/', methods=['GET','POST'])
@login_required  # 校验登陆
def info():
    if request.method == 'GET':
        pass
    if request.method == 'POST':    # 通过ajax post请求传值
        old_password = request.form.get('old_pwd')
        new_password = request.form.get('new_pwd')
        new_password2 = request.form.get('new_pwd2')
        if check_password_hash(request.user.pwd, old_password ) == False:  # request:装饰器里绑定了user
            return jsonify({'res':0})
        if new_password != new_password2:
            return jsonify({'res':-1})
        # 保存修改
        request.user.pwd = generate_password_hash(new_password)
        request.user.save_update()
        return jsonify({'res':1})



@bblue.route('/create/',methods=['GET'])
def create_db():
    # 在数据库中生成表
    # 将模型映射成数据库的表(对第一次使用有用)
    db.create_all()
    return '创建表成功'

@bblue.route('/drop/',methods=['GET'])
def drop_db():
    # 删除数据库中所有的表
    db.drop_all()
    return '删除表成功'

blog/web/views.py
import math

from flask import Blueprint, request, render_template,redirect,\
    url_for
from flask.json import jsonify
from sqlalchemy import or_,and_,not_

from back.models import Article, Atc_type

# 第一步: 生成蓝图对象
# 蓝图用于管理路由
wblue = Blueprint('web', __name__)



# 默认渲染分页第一页
def default_page():
    atcs_all = Article.query.filter().all()
    pages = list(range(math.ceil(len(atcs_all) / 5)))  # 计算应该显示的页数
    # 默认显示第一页的数据
    atcs = Article.query.order_by(-Article.create_time).offset(0).limit(5).all()
    res = [atcs_all, pages, atcs]
    return res

# ajax分页
def ajax_page(atcs):
    atcss = []
    for atc in atcs:
        atc_dict = {}
        atc_dict['id'] = atc.id
        atc_dict['title'] = atc.title
        atc_dict['desc'] = atc.desc
        atc_dict['content'] = atc.content
        atc_dict['create_time'] = atc.create_time.strftime('%Y-%m-%d %X')
        atc_dict['type'] = atc.type  # type保存的时类型的id
        atc_dict['uid'] = atc.uid
        atc_dict['tname'] = atc.tp.tname  # 获取类型名
        atcss.append(atc_dict)
    # return jsonify({'status':200})
    return jsonify({'atcss': atcss})



# 网站主页
@wblue.route('/home/',methods=['GET'])
def home():
    # 显示左侧栏目分类
    types = Atc_type.query.filter().all()
    res = default_page()
    return render_template('web/home.html', types=types, pages=res[1], atcs=res[2])


# 相册
@wblue.route('/photo/',methods=['GET'])
def photo():

    return render_template('web/photo.html')


# 文章分享主页
@wblue.route('/share/',methods=['GET','POST'])
def share():
    if request.method == 'GET':
        # 显示左侧文章分类
        types = Atc_type.query.filter().all()
        # 最近更新
        recent_atcs = Article.query.order_by(-Article.create_time).offset(0).limit(8).all()
        # 默认显示第一页文章数据
        res = default_page()
        return render_template('web/share.html', types=types, pages=res[1], atcs=res[2],recent_atcs=recent_atcs)

    if request.method == 'POST':
        page = int(request.form.get('page'))
        atcs = Article.query.order_by(-Article.create_time).offset((page - 1) * 5).limit(5).all()
        return ajax_page(atcs)


# 所选栏目的所有文章界面
@wblue.route('/share/<string:tname>/',methods=['GET', 'POST'])
def category(tname):
    if request.method == 'GET':
        # 显示左侧栏目分类
        types = Atc_type.query.filter().all()
        # 显示该类所有文章
        type = Atc_type.query.filter(Atc_type.tname == tname).first() #查找到指定类的对象
        pages = list(range(math.ceil(len(type.atcs) / 5)))  # 计算应该显示的页数
        # 默认显示第一页的数据
        atcs = Article.query.filter(Article.type==type.id).order_by(-Article.create_time).offset(0).limit(5).all()
        # 最近更新
        recent_atcs = Article.query.order_by(-Article.create_time).offset(0).limit(8).all()
        return render_template('web/share.html', atcs=atcs, types=types, pages=pages, recent_atcs=recent_atcs)  #类型对象.关联关系(atcs) 得到所有该类文章
    if request.method == 'POST':
        page = int(request.form.get('page'))
        type = Atc_type.query.filter(Atc_type.tname == tname).first()  # 查找到指定类的对象
        atcs = Article.query.filter(Article.type==type.id).order_by(-Article.create_time).offset((page - 1) * 5).limit(5).all()
        return ajax_page(atcs)


# 显示选定文章的内容界面
@wblue.route('/share/show_atc/<int:id>/',methods=['GET'])
def show_atc(id):
    # 显示左侧栏目分类
    types = Atc_type.query.filter().all()
    # 显示文章内容
    atc = Article.query.filter(Article.id == id).first()
    # 最近更新
    recent_atcs = Article.query.order_by(-Article.create_time).offset(0).limit(8).all()
    return render_template('web/share.html', atc=atc, types=types, recent_atcs=recent_atcs)


# 关于我
@wblue.route('/about/',methods=['GET'])
def about():
        return render_template('web/about.html')


@wblue.route('/info/',methods=['GET'])
def info():
        return render_template('web/info.html')

blog/templates/back/article.html
{% extends 'back/base_main.html' %}

{% block title %}
  文章 - 博客管理系统
{% endblock %}



{% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
          <form action="/back/del_all_atc/" method="post" >
            <h1 class="page-header">操作</h1>
            <ol class="breadcrumb">
              <li><a href="/back/add-article/">增加文章</a></li>
            </ol>
            <h1 class="page-header">管理 <span class="badge"> {{ atcs_all | length }} </span></h1>
            <div class="table-responsive">
              <table class="table table-striped table-hover">
                <thead>
                  <tr>
                    <th><span class="glyphicon glyphicon-th-large"></span> <span class="visible-lg">选择</span></th>
                    <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">标题</span></th>
                    <th><span class="glyphicon glyphicon-list"></span> <span class="visible-lg">栏目</span></th>
                    <th><span class="glyphicon glyphicon-time"></span> <span class="visible-lg">日期</span></th>
                    <th><span class="glyphicon glyphicon-pencil"></span> <span class="visible-lg">操作</span></th>
                  </tr>
                </thead>
                <tbody id="tbody">


                  {% if atcs %}    {# 若不为空就显示 #}
                     {% for atc in atcs %}
                      <tr id="list">
                         <td><input type="checkbox" class="input-control" name="checkbox[]" value= {{ atc.id }} /></td>
                         <td class="article-title"> {{ atc.title }} </td>
                          <!--文章对象.tp(反向查找)得到文章类型对象.tname-->
                         <td> {{ atc.tp.tname }} </td>
                         <td> {{ atc.create_time }} </td>
                         <td><a href="{{ url_for('first.update_article', id=atc.id) }}">修改</a> <a href="{{ url_for('first.del_atc', id=atc.id) }}" rel="6">删除</a></td>
                      </tr>
                      {% endfor %}
                  {% endif %}

                </tbody>
              </table>
            </div>
            <footer class="message_footer">
              <nav>
                <div class="btn-toolbar operation" role="toolbar">
                  <div class="btn-group" role="group"> <a class="btn btn-default" onClick="select()">全选</a> <a class="btn btn-default" onClick="reverse()">反选</a> <a class="btn btn-default" onClick="noselect()">不选</a> </div>
                  <div class="btn-group" role="group">
                    <button type="submit" class="btn btn-default" data-toggle="tooltip" data-placement="bottom" title="删除全部选中" name="checkbox_delete">删除</button>
                  </div>
                </div>
                <ul id='yema' class="pagination pagenav">
                  <!--<li class="disabled"><a aria-label="Previous"> <span aria-hidden="true">&laquo;</span> </a> </li>-->

                    <!--进入article时默认显示分页的第一页-->
                    {% for page in pages %}
                        {% if loop.first  %}      {# loop.first:是否第一次循环,等同page=0时 #}
                           <li class="active"><a href="#">{{ page+1 }}</a></li>
                            {% else %}
                                <li><a href="#">{{ page+1 }}</a></li>
                        {% endif %}
                    {% endfor %}

                  <!--<li><a href="#" aria-label="Next"> <span aria-hidden="true">&raquo;</span> </a> </li>-->
                </ul>
              </nav>
            </footer>
          </form>
        </div>
{% endblock %}


{% block js2 %}
<script>
  $('#category li').eq(1).addClass('active').siblings().removeClass('active')
</script>
    <script src="/static/back/js/bootstrap.min.js"></script>
    <script src="/static/back/js/admin-scripts.js"></script>
    <script>
        $(function (){
            //  给page节点添加点击
            $('#yema li').click(function () {
                $(this).addClass('active').siblings().removeClass('active')
                var index = $(this).index()+1

                get_atc(index)
            })

            // 获取点击对应页的文章
            function get_atc(page){
                $.post('/back/article/', {'page':page}, function (data) {
                    $('#tbody').empty()
                    var atcss = data.atcss
                    // console.log(atcss)
                    for(var i=0;i<atcss.length;i++) {
                        var id = atcss[i].id
                        var title = atcss[i].title
                        var tname = atcss[i].tname
                        var cretime = atcss[i].create_time

                        tr = $('<tr></tr>')
                        $('<td><input type="checkbox" class="input-control" name="checkbox[]" value= "'+id+'"  /></td>').appendTo(tr)
                        $('<td class="article-title">' + title +'</td>').appendTo(tr)
                        $('<td>' + tname + '</td>').appendTo(tr)
                        $('<td>' + cretime + '</td>').appendTo(tr)
                        $('<td><a href="/back/update-article/' + id + '/" >修改</a> <a href="/back/del-atc/' + id +'/" rel="6">删除</a></td>').appendTo(tr)
                        tr.appendTo('#tbody')

                    }

                })
            }

        })
    </script>




    <script>
    //是否确认删除
    $(function(){
        $("#main table tbody tr td a").click(function(){
            var name = $(this);
            var id = name.attr("rel"); //对应id
            if (event.srcElement.outerText == "删除")
            {
                if(window.confirm("此操作不可逆，是否确认？"))
                {
                    $.ajax({
                        type: "POST",
                        url: "/Article/delete",
                        data: "id=" + id,
                        cache: false, //不缓存此页面
                        success: function (data) {
                            window.location.reload();
                        }
                    });
                };
            };
        });
    });
    </script>
{% endblock %}

blog/templates/back/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>

        {% block title %}

        {% endblock %}




    </title>

        {% block css %}

        {% endblock %}


        {% block js1 %}

        {% endblock %}

</head>
<body class="user-stitleelect">
    <section class="container-fluid">

    {%  block header  %}

    {%  endblock %}


    {% block aside %}

    {% endblock %}

    <div class="row">

    {% block content %}

    {% endblock %}

      </div>
    </section>


    {% block dialogs %}

    {% endblock %}


    {% block js2 %}

    {% endblock %}

</body>
</html>

blog/templates/back/category.html
{% extends 'back/base_main.html' %}

{% block title %}
  栏目 - 博客管理系统
{% endblock %}


{% block link %}
  <link rel="stylesheet" type="text/css" href="/static/back/css/font-awesome.min.css">
{% endblock %}



{% block content%}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <div class="row">
        <div class="col-md-5">
          <h1 class="page-header">添加</h1>
          <form action="" method="post" autocomplete="off">
            <div class="form-group">
              <label for="category-name">栏目名称</label>
              <input type="text" id="category-name" name="name" class="form-control" placeholder="在此处输入栏目名称" required autocomplete="off">
              <span class="prompt-text">这将是它在站点上显示的名字。</span> </div>
            <div class="form-group">
              <label for="category-keywords">关键字</label>
              <input type="text" id="category-keywords" name="keywords" class="form-control" placeholder="在此处输入栏目关键字" autocomplete="off">
              <span class="prompt-text">关键字会出现在网页的keywords属性中。</span> </div>
            <div class="form-group">
              <label for="category-describe">描述</label>
              <textarea class="form-control" id="category-describe" name="describe" rows="4" autocomplete="off"></textarea>
              <span class="prompt-text">描述会出现在网页的description属性中。</span> </div>

            <button class="btn btn-primary" type="submit" name="submit">添加新栏目</button>
          </form>
        </div>
        <div class="col-md-7">
          <h1 class="page-header">管理 <span class="badge">{{ atc_types | length }}</span></h1>
          <div class="table-responsive">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th><span class="glyphicon glyphicon-paperclip"></span> <span class="visible-lg">ID</span></th>
                  <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">名称</span></th>
                  <th><span class="glyphicon glyphicon-pushpin"></span> <span class="visible-lg">总数</span></th>
                  <th><span class="glyphicon glyphicon-pencil"></span> <span class="visible-lg">操作</span></th>
                </tr>
              </thead>
              <tbody>

                {% if atc_types %}
                  {% for atc_type in atc_types %}
                    <tr>
                      <td> {{ atc_type.id }} </td>
                      <td> {{ atc_type.tname }} </td>
                      <td> {{ atc_type.atcs | length }} </td>
                      <td><a href="{{ url_for('first.update_category', id=atc_type.id) }}">修改</a> <a href="{{ url_for('first.del_type', id=atc_type.id) }}" rel="5">删除</a></td>
                    </tr>
                  {% endfor %}
                {% endif %}

              </tbody>
            </table>
        </div>
      </div>
    </div>
{% endblock %}


{% block js2 %}
<script>
  $('#category li').eq(2).addClass('active').siblings().removeClass('active')
</script>
    <script src="/static/back/js/bootstrap.min.js"></script>
    <script src="/static/back/js/admin-scripts.js"></script>
    <script>
    //是否确认删除
    $(function(){
        $("#main table tbody tr td a").click(function(){
            var name = $(this);
            var id = name.attr("rel"); //对应id
            if (event.srcElement.outerText === "删除")
            {
                if(window.confirm("此操作不可逆，是否确认？"))
                {
                    $.ajax({
                        type: "POST",
                        url: "/Category/delete",
                        data: "id=" + id,
                        cache: false, //不缓存此页面
                        success: function (data) {
                            window.location.reload();
                        }
                    });
                };
            };
        });
    });
    </script>

{% endblock %}

blog/templates/back/login_zd.html
{% extends 'back/base_main.html' %}


{% block title %}
  登陆-博客管理系统
{% endblock %}


{% block css %}
  {{ super() }}
  <link rel="stylesheet" type="text/css" href="/static/back/css/login.css">
{% endblock %}


{% block header %}

{% endblock %}


{% block aside %}

{% endblock %}


{% block dialogs %}

{% endblock %}



{% block content %}
 {{ err | safe }}

  <div class="container">
    <div class="siteIcon"><img src="images/icon/icon.png" alt="" data-toggle="tooltip" data-placement="top" title="欢迎使用异清轩博客管理系统" draggable="false" /></div>
    <form action="" method="post" autocomplete="off" class="form-signin">
      <h2 class="form-signin-heading">管理员登录</h2>
      <label for="userName" class="sr-only">用户名</label>
      <input type="text" id="userName" name="username" class="form-control" placeholder="请输入用户名" required autofocus autocomplete="off" maxlength="10">
      <label for="userPwd" class="sr-only">密码</label>
      <input type="password" id="userPwd" name="userpwd" class="form-control" placeholder="请输入密码" required autocomplete="off" maxlength="18">
      <button style="width:140px; display: inline-block" class="btn btn-lg btn-primary btn-block" type="submit" id="signinSubmit">登录</button>
      <a href="{{ url_for('first.register') }}"><button style="width:140px; display: inline-block; float: right" class="btn btn-lg btn-primary btn-block" type="button" id="signinSubmit2">去注册</button></a>

    </form>
  </div>
{% endblock %}


{% block js2 %}
  <script src="/static/back/js/bootstrap.min.js"></script>
  <script>
$('[data-toggle="tooltip"]').tooltip();
window.oncontextmenu = function(){
	//return false;
};
$('.siteIcon img').click(function(){
	window.location.reload();
});
$('#signinSubmit').click(function(){
	if($('#userName').val() === ''){
		$(this).text('用户名不能为空');
	}else if($('#userPwd').val() === ''){
		$(this).text('密码不能为空');
	}else{
		$(this).text('请稍后...');
	}
});
</script>
{% endblock %}